--------------------------------------------------------
--  Fichier créé - jeudi-novembre-04-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "AHMED"."CLIENT" 
   (	"CIN" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"MAIL" VARCHAR2(20 BYTE), 
	"TEL" NUMBER, 
	"ADRESSE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FACTURE
--------------------------------------------------------

  CREATE TABLE "AHMED"."FACTURE" 
   (	"REFERENCE" NUMBER, 
	"ETAT" VARCHAR2(20 BYTE), 
	"NOMCL" VARCHAR2(20 BYTE), 
	"PRIX" NUMBER, 
	"MAILCL" VARCHAR2(20 BYTE), 
	"COLUMN1" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PERSONNEL
--------------------------------------------------------

  CREATE TABLE "AHMED"."PERSONNEL" 
   (	"CINEMP" NUMBER, 
	"NOMEMP" VARCHAR2(20 BYTE), 
	"PRENOMEMP" VARCHAR2(20 BYTE), 
	"TELEMP" NUMBER, 
	"NOMBRECONGES" NUMBER, 
	"ETAT" VARCHAR2(20 BYTE), 
	"COLUMN8" VARCHAR2(20 BYTE), 
	"DATENAIS" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SPONSOR
--------------------------------------------------------

  CREATE TABLE "AHMED"."SPONSOR" 
   (	"MATRICULEFISCALE" VARCHAR2(20 BYTE), 
	"MAILPART" VARCHAR2(20 BYTE), 
	"TELPART" VARCHAR2(20 BYTE), 
	"ADRESSEPART" VARCHAR2(20 BYTE), 
	"ETAT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STOCK
--------------------------------------------------------

  CREATE TABLE "AHMED"."STOCK" 
   (	"NOMPIECE" VARCHAR2(20 BYTE), 
	"MARQUEPIECE" VARCHAR2(20 BYTE), 
	"PRIX" NUMBER, 
	"FOURNISSEUR" VARCHAR2(20 BYTE), 
	"DATEIMPOR" DATE, 
	"QUANTITE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VOITURE
--------------------------------------------------------

  CREATE TABLE "AHMED"."VOITURE" 
   (	"MATRICULE" NUMBER(20,0), 
	"NBVISITES" NUMBER, 
	"MARQUE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into AHMED.CLIENT
SET DEFINE OFF;
REM INSERTING into AHMED.FACTURE
SET DEFINE OFF;
REM INSERTING into AHMED.PERSONNEL
SET DEFINE OFF;
REM INSERTING into AHMED.SPONSOR
SET DEFINE OFF;
REM INSERTING into AHMED.STOCK
SET DEFINE OFF;
REM INSERTING into AHMED.VOITURE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AHMED"."TABLE1_PK" ON "AHMED"."CLIENT" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FACTURE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AHMED"."FACTURE_PK" ON "AHMED"."FACTURE" ("REFERENCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SPONSOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AHMED"."SPONSOR_PK" ON "AHMED"."SPONSOR" ("MATRICULEFISCALE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index STOCK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AHMED"."STOCK_PK" ON "AHMED"."STOCK" ("NOMPIECE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "AHMED"."TABLE1_PK1" ON "AHMED"."VOITURE" ("MATRICULE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "AHMED"."CLIENT" MODIFY ("ADRESSE" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."CLIENT" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AHMED"."CLIENT" MODIFY ("TEL" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."CLIENT" MODIFY ("MAIL" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."CLIENT" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."CLIENT" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."CLIENT" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FACTURE
--------------------------------------------------------

  ALTER TABLE "AHMED"."FACTURE" ADD CONSTRAINT "FACTURE_PK" PRIMARY KEY ("REFERENCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AHMED"."FACTURE" MODIFY ("COLUMN1" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."FACTURE" MODIFY ("MAILCL" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."FACTURE" MODIFY ("PRIX" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."FACTURE" MODIFY ("NOMCL" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."FACTURE" MODIFY ("ETAT" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."FACTURE" MODIFY ("REFERENCE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERSONNEL
--------------------------------------------------------

  ALTER TABLE "AHMED"."PERSONNEL" MODIFY ("DATENAIS" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."PERSONNEL" MODIFY ("COLUMN8" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."PERSONNEL" MODIFY ("ETAT" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."PERSONNEL" MODIFY ("NOMBRECONGES" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."PERSONNEL" MODIFY ("TELEMP" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."PERSONNEL" MODIFY ("PRENOMEMP" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."PERSONNEL" MODIFY ("NOMEMP" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."PERSONNEL" MODIFY ("CINEMP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SPONSOR
--------------------------------------------------------

  ALTER TABLE "AHMED"."SPONSOR" MODIFY ("ETAT" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."SPONSOR" MODIFY ("ADRESSEPART" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."SPONSOR" MODIFY ("TELPART" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."SPONSOR" MODIFY ("MAILPART" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."SPONSOR" MODIFY ("MATRICULEFISCALE" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."SPONSOR" ADD CONSTRAINT "SPONSOR_PK" PRIMARY KEY ("MATRICULEFISCALE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STOCK
--------------------------------------------------------

  ALTER TABLE "AHMED"."STOCK" ADD CONSTRAINT "STOCK_PK" PRIMARY KEY ("NOMPIECE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AHMED"."STOCK" MODIFY ("QUANTITE" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."STOCK" MODIFY ("DATEIMPOR" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."STOCK" MODIFY ("FOURNISSEUR" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."STOCK" MODIFY ("PRIX" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."STOCK" MODIFY ("MARQUEPIECE" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."STOCK" MODIFY ("NOMPIECE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VOITURE
--------------------------------------------------------

  ALTER TABLE "AHMED"."VOITURE" ADD CONSTRAINT "VOITURE_PK" PRIMARY KEY ("MATRICULE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AHMED"."VOITURE" MODIFY ("MARQUE" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."VOITURE" MODIFY ("NBVISITES" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."VOITURE" MODIFY ("MATRICULE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table FACTURE
--------------------------------------------------------

  ALTER TABLE "AHMED"."FACTURE" ADD CONSTRAINT "CINCLIE" FOREIGN KEY ("REFERENCE")
	  REFERENCES "AHMED"."CLIENT" ("CIN") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PERSONNEL
--------------------------------------------------------

  ALTER TABLE "AHMED"."PERSONNEL" ADD CONSTRAINT "CINCLI" FOREIGN KEY ("CINEMP")
	  REFERENCES "AHMED"."CLIENT" ("CIN") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VOITURE
--------------------------------------------------------

  ALTER TABLE "AHMED"."VOITURE" ADD CONSTRAINT "CINCL" FOREIGN KEY ("NBVISITES")
	  REFERENCES "AHMED"."CLIENT" ("CIN") ENABLE;
